changeLogFile=changelog/liquibase-output.xml
url=jdbc:postgresql://localhost:5432/postgres
username=postgres
password=$Okol622
driver=org.postgresql.Driver
defaultSchemaName=sb_db
classpath=C:/Liquibase/lib/postgresql-42.6.0.jar