changeLogFile=changelog/liquibase-output.xml
url=jdbc:postgresql://localhost:5432/oris2_db
username=oris2_db
password=$Okol622
driver=org.postgresql.Driver
classpath=C:/Liquibase/lib/postgresql-42.6.0.jar