spring.database=POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/oris2_db
spring.datasource.username=oris
spring.datasource.password=$Okol622
spring.datasource.driver-class-name=org.postgresql.Driver